### PR TITLE
fix: Issue where the section height on the about section had different spacing between top and bottom areas

### PR DESCRIPTION
**Pull request by inovux**
closes issue #61 

### Description

The spacing on the about page was wrong, the top side had more white space than the bottom. This PR will fix this issue.

### CODE REVIEW

**Comment by inovux** [comment]
@varun-singhh Could you review my PR :)?

**Comment by kaustubhai** [comment]
Hey @inovux, I cannot see how is this solving the problem. Can you elaorate

**Comment by inovux** [comment]
@kaustubhai sorry I guess I forgot one of the media queries used on mobile

**Comment by inovux** [comment]
@kaustubhai the spacing should be the same now on all screen sizes. If this is still incorrect can you please explain then what it is you want to be fixed because I have no idea then:)

**Comment by kaustubhai** [comment]
See the spacing on all screen sizes is same, but it is not according to the design. 
In a div, the content should have equal top and bottom padding right? However it does not seem to be the case with this div.
Let me know if still it is not clear

**Comment by inovux** [comment]
@kaustubhai if it is not according to the design, then where can I find the design so I can adjust it?

**Comment by varun-singhh** [comment]
@inovux your PR is not valid. Actually, you are behind the master branch, first, you need to pull from the master branch then edit the changes as mentioned by @kaustubhai

**Comment by inovux** [comment]
@varun-singhh I understand its not valid. But not sure what the design should be looking like exactly? How big should the spacing be and where is the spacing off exactly? I cannot really figure out what has to be done here.

**Comment by varun-singhh** [comment]
Surely will let you know the requirements within 48hrs

**Comment by varun-singhh** [comment]
> @varun-singhh I understand its not valid. But not sure what the design should be looking like exactly? How big should the spacing be and where is the spacing off exactly? I cannot really figure out what has to be done here.

@kaustubhai please look into it.

**Pull request closed without merging**
